# Generated by Django 4.1.5 on 2023-01-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="views", field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Name of Article"
            ),
        ),
    ]
