# Generated by Django 4.1.5 on 2023-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0002_article_views_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="slug", field=models.SlugField(blank=True),
        ),
    ]
