# Generated by Django 4.1.5 on 2023-01-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0003_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
