# Generated by Django 4.1.5 on 2023-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover",
            field=models.FileField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="Cover image"
            ),
        ),
    ]
