# Generated by Django 4.1.5 on 2023-01-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0005_article_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="Cover image"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="bloggy.tag", verbose_name="Tags"
            ),
        ),
    ]
