# Generated by Django 4.1.5 on 2023-01-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0006_tag_alter_article_cover_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="escaped_body",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
