# Generated by Django 4.1.5 on 2023-01-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggy", "0007_article_escaped_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="stem_body",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
